### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'wiki.zh.text.vector'

### ISSUE THREAD

**Issue by lyicy** [AimeeLee77/keyword_extraction#2]
下载完 直接运行python  keyextract_word2vec_1.py 报“IOError: [Errno 2] No such file or directory: 'wiki.zh.text.vector'” 怎么解决?

**Comment by Ryze789** [comment]
请问怎么解决这个问题

**Comment by weilifan** [comment]
同问怎么解决
